add instructions for apple-silicon installation
ejegrova/linuxadmin pull request #13
Opened 2024-03-01 23:23 UTC by tnevrlka

Přidán návrh návodu k zprovoznění virtuálního stroje na počítačích Apple s procesory Apple Silicon.

* Snažil jsem se dodržet styl ostatních návodů, ale přesné pokyny jsem nenašel (tykání, velké T?, vyhýbání se použití rodů)
* Návod je hodně vyčerpávající - myšlenkou je, že je určen i pro kouče co nikdy nepoužívali macOS a musí se snažit pomoct. Nebráním se zásadnímu zkrácení.
* Nevím jestli je potřeba dělat něco s `info.yml` souborem
* Obrázky jsou vloženy v čistém Markdownu, uvítal bych podrobnější info jak je vkládat. Nevím jak přesně funguje
```
{{ figure(
    img=static('fedora-install-01.png'),
    alt='Instalace #1',
) }}
```

2024-03-04 09:13 UTC, ZelenyMartin commented
Ahoj, díky moc za příspěvek!

* O nějakých instrukcích ke stylu psaní nevím. Určitě je vhodné držet se existujícího.
* Prosím tě, z nějakého důvodu se tam používají ty jinja templaty `{{ figure() }}` a `{{ subpage_url() }}`, tak bych se pokud, možno, držel tohoto způsobu.
* Do té sekce `subpages` v `info.yaml` by se to učitě taky mělo přidat.

2024-03-04 20:40 UTC, tnevrlka commented
Obrázky i subpages by měly být přepsány do Jinja formátu (a zkompiluje se to, tak snad správně). Nejde se někde podívat jak ta stránka vypadá?

2024-03-05 08:35 UTC, ZelenyMartin requested changes
Díky moc! Nahodil jsem nějaký commenty s návrhy změn. Stačí, když tam klikneš "Commit suggestion", a pak to všechno squashnem.

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/apple-silicon.md
> +Jestli už víš, že Tvé zařízení používá procesor Intel, můžeš přestat číst tento návod a přejdi [sem]({{ subpage_url('virtualbox.md') }}).
```suggestion
Jestli už víš, že Tvé zařízení používá procesor Intel, můžeš přestat číst tento návod a přejdi [sem]({{ subpage_url('virtualbox') }}).
```
V ostatních výskytech volání té funkce není přípona `.md`.

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/apple-silicon.md
> +- Pokud obsahuje nějakou zmínku o "Intelu", pak se tě tento návod netýká a můžeš pokračovat [na tomto odkaze]({{ subpage_url('virtualbox.md') }}).
```suggestion
- Pokud obsahuje nějakou zmínku o "Intelu", pak se tě tento návod netýká a můžeš pokračovat [na tomto odkaze]({{ subpage_url('virtualbox') }}).
```

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/apple-silicon.md
> +Vzhledem k omezením spojených s architekturou Apple Silicon procesorů bude nejlepší použít nástroj zvaný [UTM]({{ subpage_url('https://mac.getutm.app') }}).
```suggestion
Vzhledem k omezením spojených s architekturou Apple Silicon procesorů bude nejlepší použít nástroj zvaný [UTM](https://mac.getutm.app).
```
Externí odkazy se tady píšou normálně.

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/apple-silicon.md
> +Jinak UTM můžeš stáhnout z [oficiálních stránek]({{ subpage_url('https://mac.getutm.app') }}) kliknutím na tlačítko "Download".
```suggestion
Jinak UTM můžeš stáhnout z [oficiálních stránek](https://mac.getutm.app) kliknutím na tlačítko "Download".
```

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/apple-silicon.md
> +Pokud si nic takového nepamatuješ, znovu si přečti [dřívější kapitolu]({{ subpage_url('index.md#stažení-obrazu-') }}) a poté se znovu vrať sem.
```suggestion
Obraz by už měl být stažen z [dřívější kapitoly]({{ subpage_url('index.md#stažení-obrazu-') }}). 
Pokud si nic takového nepamatuješ, znovu si přečti [dřívější kapitolu]({{ subpage_url('index.md#stažení-obrazu-') }}) a poté se znovu vrať sem.
```
Nemá tam být ta přípona `.md` a ty kotvy se nedělají automaticky. Jinde v kódu je to jako:
```
{{ anchor('install-system') }}
# Instalace systému
```
a pak se to referencuje
```
Pokračuj [instalací systému]({{ subpage_url('index#install-system') }}).
```

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/apple-silicon.md
> +Samotná instalace je popsána v kapitole [instalace systému]({{ subpage_url('index.md#instalace-systému') }} ).
```suggestion
Samotná instalace je popsána v kapitole [instalace systému]({{ subpage_url('index#install-system') }}).
```

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/index.md
> +si stáhni z [getfedora.org]({{ subpage_url('https://getfedora.org/cs/workstation/download/') }}) –
```suggestion
si stáhni z [getfedora.org](https://getfedora.org/cs/workstation/download) –
```

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/index.md
> +Pokud máš macOS a nevíš jestli máš procesor Intel, přečti si nejdříve [Jak poznat který procesor máš]({{ subpage_url('apple-silicon.md#jak-poznat-který-procesor-máš') }}) a poté se vrať zpět sem.
Příponu `.md` pryč a dát existující kotvu.

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/index.md
> +* Pokud máš macOS a nevíš jestli máš procesor Intel, přečti si [instalace na Apple Silicon]({{ subpage_url('apple-silicon.md') }})
```suggestion
* Pokud máš macOS a nevíš jestli máš procesor Intel, přečti si [instalace na Apple Silicon]({{ subpage_url('apple-silicon') }})
```

2024-03-05 08:35 UTC, ZelenyMartin commented on lessons/linuxadmin/installation/info.yml
> +        subtitle: Instalace na Apple Silicon
```suggestion
        subtitle: Instalace na Apple Silicon
```
Chybí znak nového řádku na konci souboru. To není extrémně zle, ale většinou by se editor měl nastavit tak, aby ten znak konce řádku na konec souboru zapisoval.

2024-03-11 17:08 UTC, tnevrlka commented
@ZelenyMartin Díky moc za cenné rady, všechno by mělo být opraveno a dokument se zdá se kompiluje

2024-03-12 09:06 UTC, ZelenyMartin approved these changes

2024-03-12 09:28 UTC, merged